### ISSUE TITLE
Stale Repo?

### ISSUE THREAD

**Issue by dav-is** [developit/preact-redux#21]
This repo hasn't seen updates in a while. Any updates?

**Comment by developit** [comment]
What type of update were you looking for? There's almost no code in this module, it just rebuilds the underlying react-redux module for Preact.

**Comment by dav-is** [comment]
I meant a verbal update on where the current issues and PRs stand. There’s some pretty old ones.

**Comment by developit** [comment]
Just did some work on it, I'll try to add some tags and a backlog project.
