### ISSUE TITLE
Tag new release

### ISSUE THREAD

**Issue by fjorgemota** [developit/preact-redux#39]
Hey.

This issue is just a reminder to tag a new release for this project, as there are already a bunch of fixes that are available only on master and that would be good to have on a tagged release, like fixes for #31 and #32, for example.

Thanks. :)

**Comment by pmkroeker** [comment]
Bump. Yes I reinstalled preact-redux and its throwing some TS errors that got fixed. Would be nice to have this released. @developit

**Comment by lauritzsh** [comment]
Any updates on a tag? It would be nice to have a tag to depend on in package.json. A new release for npm would also be very nice to have.
